# Generated by Django 5.2.15 on 2026-06-14 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], db_index=True, default='DRAFT', max_length=10)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GRN',
                'verbose_name_plural': 'GRNs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fulfilled_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product')),
            ],
            options={
                'verbose_name': 'PO Line',
                'verbose_name_plural': 'PO Lines',
            },
        ),
        migrations.CreateModel(
            name='GRNLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_received', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(blank=True, default='', max_length=255)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.grn')),
                ('variance_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reasoncode')),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.poline')),
            ],
            options={
                'verbose_name': 'GRN Line',
                'verbose_name_plural': 'GRN Lines',
            },
        ),
        migrations.CreateModel(
            name='PurchaseBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], db_index=True, default='DRAFT', max_length=20)),
                ('total_estimated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Budget',
                'verbose_name_plural': 'Purchase Budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('est_unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchasebudget')),
            ],
            options={
                'verbose_name': 'Budget Line',
                'verbose_name_plural': 'Budget Lines',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SENT', 'Sent'), ('MANUAL_CONTACT_REQUIRED', 'Manual Contact Required'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CLOSED', 'Closed')], db_index=True, default='CREATED', max_length=30)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='procurement/po_pdfs/')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.purchasebudget')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masterdata.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSendLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('BOUNCED', 'Bounced'), ('NONE_NO_EMAIL', 'None — No Email')], default='NONE_NO_EMAIL', max_length=20)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='procurement.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Send Log',
                'verbose_name_plural': 'PO Send Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='poline',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='grn',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='procurement.purchaseorder'),
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_ref', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('file', models.FileField(blank=True, null=True, upload_to='procurement/invoices/')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='procurement.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='masterdata.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
                'verbose_name_plural': 'Supplier Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('DISCREPANCY', 'Discrepancy'), ('DISPUTED', 'Disputed'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved')], db_index=True, default='MATCHED', max_length=20)),
                ('discrepancies', models.JSONField(default=dict)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.purchaseorder')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='procurement.supplierinvoice')),
            ],
            options={
                'verbose_name': 'Invoice Match',
                'verbose_name_plural': 'Invoice Matches',
                'ordering': ['-created_at'],
            },
        ),
    ]
