# Generated by Django 5.2.15 on 2026-06-14 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuenote',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuenote',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_out', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='issuenoteline',
            name='issue_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.issuenote'),
        ),
        migrations.AddField(
            model_name='issuenoteline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='started_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='stocktakeline',
            name='stock_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='masterdata.location'),
        ),
        migrations.AddField(
            model_name='transferline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product'),
        ),
        migrations.AddField(
            model_name='transferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.transfer'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('product', 'location'), name='unique_balance_per_product_location'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'location', 'posted_at'], name='ledger_prod_loc_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['document_type', 'document_id'], name='ledger_document_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktakeline',
            constraint=models.UniqueConstraint(fields=('stock_take', 'product'), name='unique_product_per_stocktake'),
        ),
    ]
