# Generated by Django 5.2.15 on 2026-06-14 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BUDGET_APPROVED', 'Budget Approved'), ('SYNC_FAILED', 'Sync Failed'), ('LOW_STOCK', 'Low Stock'), ('ORDER_RETURNED', 'Order Returned'), ('APPROVAL_PENDING', 'Approval Pending'), ('INSUFFICIENT_STOCK', 'Insufficient Stock')], max_length=30)),
                ('subject_id', models.UUIDField(blank=True, null=True)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
