global:
  resolve_timeout: 5m

route:
  receiver: team-ops
  group_by: [alertname, service]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  routes:
    - matchers:
        - route="oncall"
      receiver: team-oncall

receivers:
  - name: team-ops
    webhook_configs:
      - url: http://host.docker.internal:5001/alerts/ops
        send_resolved: true

  - name: team-oncall
    webhook_configs:
      - url: http://host.docker.internal:5001/alerts/oncall
        send_resolved: true
