# Generated by Django 5.2.15 on 2026-06-14 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_id', models.UUIDField()),
                ('scope', models.CharField(blank=True, choices=[('TRANSFER', 'Inter-unit transfer'), ('WASTAGE', 'Wastage / breakage'), ('ADJUSTMENT', 'Stock-take adjustment'), ('EXTRA_USAGE', 'Extra ingredient usage')], default='', max_length=20)),
                ('threshold_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVESTIGATION', 'Under investigation')], db_index=True, default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(max_length=40)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('response_snapshot', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
            ],
            options={
                'verbose_name': 'Idempotency Key',
                'verbose_name_plural': 'Idempotency Keys',
            },
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('POS_MODE', 'POS ingestion mode'), ('POS_ENDPOINT', 'POS endpoint'), ('PASTEL_MODE', 'Pastel sync mode'), ('PASTEL_CREDENTIALS', 'Pastel credentials'), ('EMAIL_GATEWAY', 'Supplier email gateway')], max_length=40, unique=True)),
                ('value', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Integration Setting',
                'verbose_name_plural': 'Integration Settings',
            },
        ),
        migrations.CreateModel(
            name='OutboxRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Outbox Record',
                'verbose_name_plural': 'Outbox Records',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReasonCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('WASTAGE', 'Wastage'), ('RETURN', 'Return'), ('OVERRIDE', 'Override'), ('ISSUE_DAY', 'Off-schedule issue'), ('VARIANCE', 'GRN variance')], db_index=True, max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reason Code',
                'verbose_name_plural': 'Reason Codes',
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ThresholdConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('TRANSFER', 'Inter-unit transfer'), ('WASTAGE', 'Wastage / breakage'), ('ADJUSTMENT', 'Stock-take adjustment'), ('EXTRA_USAGE', 'Extra ingredient usage')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Threshold Configuration',
                'verbose_name_plural': 'Threshold Configurations',
            },
        ),
    ]
