# Generated by Django 5.2.15 on 2026-06-14 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_ref', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('INGESTED', 'Ingested'), ('IN_PREPARATION', 'In preparation'), ('READY', 'Ready'), ('SERVED', 'Served'), ('RETURNED', 'Returned')], db_index=True, default='INGESTED', max_length=20)),
                ('flagged_insufficient_stock', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos_code', models.CharField(max_length=50)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('modifiers', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INGESTED', 'Ingested'), ('IN_PREPARATION', 'In preparation'), ('READY', 'Ready'), ('SERVED', 'Served'), ('RETURNED', 'Returned')], max_length=20)),
            ],
            options={
                'verbose_name': 'Order Status Event',
                'verbose_name_plural': 'Order Status Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutOfStockFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Out-of-Stock Flag',
                'verbose_name_plural': 'Out-of-Stock Flags',
                'ordering': ['-created_at'],
            },
        ),
    ]
