# Generated by Django 5.2.15 on 2026-06-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('kitchen', '0001_initial'),
        ('menu', '0001_initial'),
        ('pos_ingest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='pos_ingest.saleevent'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='recipe_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.recipeversion'),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='kitchen.order'),
        ),
        migrations.AddField(
            model_name='orderstatusevent',
            name='reason_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.reasoncode'),
        ),
    ]
