# Generated by Django 5.2.15 on 2026-06-14 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('kitchen', '0002_initial'),
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WastageEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('EXTRA_USAGE', 'Extra usage'), ('BREAKAGE', 'Breakage'), ('SPOILAGE', 'Spoilage')], max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.location')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wastage_entries', to='kitchen.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.product')),
                ('reason_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.reasoncode')),
            ],
            options={
                'verbose_name': 'Wastage Entry',
                'verbose_name_plural': 'Wastage Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry_type', 'created_at'], name='wastage_type_created_idx'), models.Index(fields=['location', 'created_at'], name='wastage_loc_created_idx')],
            },
        ),
    ]
