# Generated by Django 5.2.15 on 2026-06-14 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplayLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Replay Log Entry',
                'verbose_name_plural': 'Replay Log Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos_sale_id', models.CharField(max_length=100, unique=True)),
                ('payload', models.JSONField()),
                ('cashier', models.CharField(blank=True, default='', max_length=100)),
                ('sold_at', models.DateTimeField()),
                ('totals', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('INGESTED', 'Ingested'), ('FLAGGED_UNKNOWN_ITEM', 'Flagged: unknown item'), ('REPLAYED', 'Replayed'), ('FAILED', 'Failed')], db_index=True, default='INGESTED', max_length=25)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sale Event',
                'verbose_name_plural': 'Sale Events',
                'ordering': ['-ingested_at'],
            },
        ),
    ]
