# Generated by Django 5.2.15 on 2026-06-14 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos_ingest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='replaylog',
            name='replayed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='replaylog',
            name='sale_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replays', to='pos_ingest.saleevent'),
        ),
    ]
